apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: namegen
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb
